# Generated by Django 5.0 on 2024-01-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_id", models.IntegerField(unique=True)),
                ("stop_code", models.IntegerField(unique=True)),
                ("stop_name", models.CharField(max_length=255)),
                ("stop_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("stop_lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("wheelchair_boarding", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.IntegerField(unique=True)),
                ("arrival_time", models.TimeField()),
                ("departure_time", models.TimeField()),
                (
                    "route_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Routes.route"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StopTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_sequence", models.IntegerField()),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Stops.stop"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Stops.trip"
                    ),
                ),
            ],
        ),
    ]
